import os
SECRET_KEY = os.getenv('SECRET_KEY', 'changeme')
SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL', 'sqlite:///cti.db')
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECURITY_PASSWORD_SALT = 'changeme'
SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False